name: Run Unit Tests

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/ -v --tb=short -m "not integration" --asyncio-mode=auto

    - name: Run unit tests with coverage
      if: matrix.python-version == '3.13'
      run: |
        pip install pytest-cov
        pytest tests/ -v --tb=short -m "not integration" --asyncio-mode=auto --cov=src/mcp_privilege_cloud --cov-report=term