name: Run Unit Tests

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pipenv dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pipenv
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies
      run: |
        pipenv install --dev --deploy

    - name: Run unit tests
      run: |
        pipenv run pytest tests/ -v --tb=short -m "not integration" --asyncio-mode=auto

    - name: Run unit tests with coverage
      if: matrix.python-version == '3.13'
      run: |
        pipenv install pytest-cov
        pipenv run pytest tests/ -v --tb=short -m "not integration" --asyncio-mode=auto --cov=src/cyberark_mcp --cov-report=term